/* ============================================================
   data/cases.js — All fictional cybercrime case data
   ============================================================ */

const CASES = [
  {
    id: "CY-2024-0047",
    title: "OPERATION GHOST WIRE",
    status: "OPEN",
    category: "Nation-State Intrusion",
    desc: "Coordinated intrusion into critical power grid infrastructure. Attackers planted dormant malware across 14 substations across the northeastern corridor. Attribution points to state-sponsored APT group.",
    date: "2024-03-15",
    lead: "Agent K. Vasquez",
    severity: 95,
    tags: ["APT", "SCADA", "Infrastructure", "Malware"],
    evidence: [
      { icon: "🖥️", name: "SUBSTATION_FIRMWARE_DUMP.bin",  desc: "Extracted firmware from compromised Siemens S7-1200 PLCs. Contains hidden rootkit payload triggered by timestamp logic.", meta: "Size: 4.2 MB | SHA256: a3f9...cc12", status: "ev-verified" },
      { icon: "📡", name: "NETWORK_PCAP_0315.cap",          desc: "24-hour packet capture from breached segment. Reveals C2 beaconing to IP 185.234.xx.xx at 3-hour intervals using DNS tunneling.", meta: "Size: 2.1 GB | Captured: 2024-03-15 00:00–23:59", status: "ev-verified" },
      { icon: "🔑", name: "STOLEN_CERTS.pem",               desc: "Three stolen X.509 certificates from a legitimate SCADA vendor, used to sign malicious firmware updates.", meta: "Cert validity: 2022–2026 | Issuer: TrustCert CA", status: "ev-verified" },
      { icon: "💾", name: "IMPLANT_STAGE2.elf",              desc: "Second-stage implant binary recovered from grid controller. Dormant until activation string received via MQTT topic.", meta: "Size: 890 KB | Compiled: Linux/ARM", status: "ev-pending" },
      { icon: "📋", name: "OPERATOR_INTERVIEW_04.docx",      desc: "Transcript from plant operator interview. Mentions unusual login prompt appearing briefly on Feb 28 — weeks before detected breach.", meta: "Interview date: 2024-04-01 | Redacted", status: "ev-verified" },
    ],
    timeline: [
      { time: "2024-02-28 03:14", event: "Initial Access",          detail: "Spear-phishing email sent to grid operator engineers. One attachment opened; macro executed initial dropper." },
      { time: "2024-03-01 11:30", event: "Lateral Movement Begins", detail: "Attacker pivoted from engineer workstation to OT network segment using stolen VPN credentials." },
      { time: "2024-03-06 04:00", event: "PLC Compromise",          detail: "14 Siemens S7-1200 PLCs infected with dormant firmware implant. No operational disruption triggered yet." },
      { time: "2024-03-15 07:22", event: "Anomaly Detected",        detail: "IDS flagged irregular MQTT traffic from substation controller. Security team initiated investigation." },
      { time: "2024-03-15 14:00", event: "NDFB Notified",           detail: "Case escalated to National Digital Forensics Bureau. Incident classified CRITICAL." },
      { time: "2024-03-18 09:00", event: "Malware Isolated",        detail: "Compromised PLCs taken offline. Backup firmware restored. Grid remains on manual operations protocol." },
      { time: "ONGOING",          event: "Attribution Analysis",    detail: "Tooling, TTPs, and C2 infrastructure linked to APT-77 (alias: STEEL VIPER). Active investigation." },
    ],
    suspects: [
      { avatar: "🕵️", alias: "VIPER-LEAD",  handle: "@null_substrate", detail: "Suspected team lead. Linked to prior attacks on European energy sector in 2021. Operates from VPN chains through Eastern Europe.", threat: "threat-high" },
      { avatar: "💻", alias: "CIRCUIT-X",   handle: "@hex_phantom",    detail: "SCADA specialist. Reverse-engineered the PLC firmware. Code signature matches malware from 2019 pipeline attack.", threat: "threat-high" },
      { avatar: "📧", alias: "SENDER-7",    handle: "@mist_relay",     detail: "Phishing infrastructure operator. Manages botnet used for spear-phishing delivery. Location: unknown.", threat: "threat-med" },
    ],
    logs: [
      { ts: "2024-03-15 07:22:03", level: "warn",  msg: "IDS ALERT: Anomalous MQTT traffic volume from node SUB-14" },
      { ts: "2024-03-15 07:22:45", level: "error", msg: "Unauthorized firmware signature detected on PLC [ID: S7-012]" },
      { ts: "2024-03-15 07:23:10", level: "crit",  msg: "INTRUSION CONFIRMED — Grid segment NORTHEAST-3 quarantined" },
      { ts: "2024-03-15 08:00:00", level: "info",  msg: "Forensic image acquisition initiated — 14 affected nodes" },
      { ts: "2024-03-15 09:15:22", level: "info",  msg: "C2 IP flagged: 185.234.117.88 — blackholed at perimeter" },
      { ts: "2024-03-15 14:00:00", level: "info",  msg: "Case escalated to NDFB — Priority: CRITICAL" },
      { ts: "2024-03-18 09:00:00", level: "info",  msg: "Affected PLCs isolated — manual failover activated" },
    ]
  },
  {
    id: "CY-2024-0031",
    title: "PROJECT SILKWORM",
    status: "CLOSED",
    category: "Financial Fraud Network",
    desc: "Multinational cryptocurrency laundering operation exploiting DEX protocols. Funds traced through 47 shell wallets across 9 blockchain networks. Three subjects arrested following 8-month investigation.",
    date: "2024-01-09",
    lead: "Agent D. Park",
    severity: 72,
    tags: ["Crypto", "Money Laundering", "DeFi", "Organized Crime"],
    evidence: [
      { icon: "💰", name: "BLOCKCHAIN_TRACE_REPORT.pdf",  desc: "Complete transaction graph showing $47M routed through layered wallet addresses. Nodes linked to Nexus Exchange accounts.", meta: "Analyzed: 2024-01-20 | Tool: CryptoTrace Pro", status: "ev-verified" },
      { icon: "💬", name: "ENCRYPTED_CHAT_LOGS.db",       desc: "Decrypted Signal-clone app messages recovered from seized devices. Contains operational planning for fund movement.", meta: "Messages: 14,823 | Period: Aug 2023 – Jan 2024", status: "ev-verified" },
      { icon: "🏦", name: "SHELL_COMPANY_DOCS.zip",       desc: "Incorporation documents for 8 front companies in Cyprus, Malta, and the BVI. All registered within 60-day window.", meta: "Doc count: 214 | Source: Seized hard drive", status: "ev-verified" },
      { icon: "📱", name: "SEIZED_DEVICE_IMG_001.dd",     desc: "Forensic image of Samsung device belonging to suspect MARQUETTE. Contains wallet seed phrases in encrypted notes app.", meta: "Device: SM-G998B | Image: 128 GB", status: "ev-verified" },
    ],
    timeline: [
      { time: "2023-05-12", event: "Operation Begins",     detail: "Fraud analytics flagged unusual DEX trading pattern. $2M moved in circular fashion through 6 wallets." },
      { time: "2023-07-03", event: "Network Mapped",       detail: "Analysis expanded. 47 wallets identified forming a layered laundering structure. Three main controllers identified." },
      { time: "2023-09-19", event: "Human Intelligence",   detail: "Undercover agent made contact with lower-level operator. Confirmed organizational hierarchy." },
      { time: "2024-01-08", event: "Warrants Executed",    detail: "Simultaneous raids in three countries. Devices seized. $3.4M in crypto assets frozen." },
      { time: "2024-01-09", event: "Case Closed",          detail: "Three subjects arrested. Charges: money laundering, wire fraud, conspiracy. Extradition proceedings ongoing for fourth." },
    ],
    suspects: [
      { avatar: "🎰", alias: "MARQUETTE",  handle: "@king_of_chains",  detail: "Operation organizer. Former quantitative analyst. Designed the wallet rotation algorithm. Arrested in Rotterdam.", threat: "threat-high" },
      { avatar: "🌐", alias: "NODESMITH",  handle: "@d3fi_ghost",       detail: "Technical lead. Built the automated swapping bots. Still at large. Last known location: Southeast Asia.", threat: "threat-high" },
      { avatar: "🏢", alias: "FRONTMAN",   handle: "@corporateclean",   detail: "Shell company registrar. Handled fiat conversion. Arrested in Valletta, Malta. Cooperating witness.", threat: "threat-low" },
    ],
    logs: [
      { ts: "2023-05-12 16:04:11", level: "warn", msg: "Fraud analytics: Circular transaction pattern detected — wallet cluster ID 7732" },
      { ts: "2023-07-03 09:30:00", level: "info", msg: "Network expansion analysis complete — 47 wallets mapped across 9 chains" },
      { ts: "2024-01-08 06:00:00", level: "crit", msg: "OPERATION LIVE — Simultaneous raids executing across 3 jurisdictions" },
      { ts: "2024-01-08 06:47:33", level: "info", msg: "Asset freeze confirmed — $3,412,000 USD equivalent in crypto holdings locked" },
      { ts: "2024-01-09 11:00:00", level: "info", msg: "Case status updated: CLOSED — 3 of 4 suspects in custody" },
    ]
  },
  {
    id: "CY-2023-0189",
    title: "OPERATION DARK HARVEST",
    status: "CLASSIFIED",
    category: "Data Exfiltration / Espionage",
    desc: "Exfiltration of classified pharmaceutical research from BioNova Laboratories. 2.3TB of proprietary gene therapy data transferred to unknown foreign server. Mole suspected within executive team.",
    date: "2023-11-02",
    lead: "REDACTED",
    severity: 99,
    tags: ["Espionage", "Insider Threat", "Data Theft", "Classified"],
    evidence: [
      { icon: "🧬", name: "EXFIL_MANIFEST_[REDACTED]",         desc: "Detailed log of all files removed from secure research partition. 2.3TB over 6 weeks via encrypted cloud sync.", meta: "Classification: SECRET | Access: LVL-5 only", status: "ev-verified" },
      { icon: "📹", name: "CCTV_ANOMALY_LOG.mp4",               desc: "Security footage showing badge access to server room at 02:14 on three consecutive Fridays. Face partially obscured.", meta: "Status: Under Analysis | Gait analysis pending", status: "ev-pending" },
      { icon: "🔒", name: "ENCRYPTED_EXFIL_TOOL.zip",           desc: "Custom exfiltration tool found on personal device. Disguised as PDF viewer. Communicates via steganographic images.", meta: "Hash: 9f3a...d882 | Compiler: Go 1.21", status: "ev-verified" },
      { icon: "❓", name: "COMMS_INTERCEPT_[REDACTED]",          desc: "[CONTENT CLASSIFIED — LEVEL 5 CLEARANCE REQUIRED]", meta: "Declassification date: INDEFINITE", status: "ev-corrupted" },
    ],
    timeline: [
      { time: "2023-09-15", event: "First Data Movement",   detail: "Unusual cloud sync traffic detected from secure research partition. Dismissed as backup error at the time." },
      { time: "2023-10-20", event: "Pattern Identified",    detail: "Security audit flagged recurring 400GB sync events on Friday nights. Escalated to CISO." },
      { time: "2023-11-01", event: "Insider Identified",    detail: "Access logs narrowed exfiltration to one of three individuals with partition access. Investigation classified." },
      { time: "2023-11-02", event: "NDFB Takes Jurisdiction", detail: "Due to national security implications, case transferred to NDFB Special Division. Details classified." },
      { time: "ONGOING",    event: "[REDACTED]",             detail: "[CONTENT CLASSIFIED — LEVEL 5 CLEARANCE REQUIRED TO VIEW]" },
    ],
    suspects: [
      { avatar: "❓", alias: "SUBJECT-ALPHA",    handle: "[REDACTED]",    detail: "Senior researcher with access to all gene therapy partitions. Travel records flagged. Under surveillance.", threat: "threat-high" },
      { avatar: "❓", alias: "SUBJECT-BETA",     handle: "[REDACTED]",    detail: "IT administrator. Provisioned elevated access 3 days before exfiltration began. Claims system error.", threat: "threat-high" },
      { avatar: "❓", alias: "UNKNOWN HANDLER",  handle: "[CLASSIFIED]",  detail: "Foreign intelligence contact suspected. Communications identified but source unattributed. Ongoing SIGINT operation.", threat: "threat-high" },
    ],
    logs: [
      { ts: "2023-11-01 00:00:00", level: "crit", msg: "[LOG CONTENT CLASSIFIED — CLEARANCE REQUIRED]" },
      { ts: "2023-11-02 00:00:00", level: "crit", msg: "[LOG CONTENT CLASSIFIED — CLEARANCE REQUIRED]" },
      { ts: "2023-11-02 08:00:00", level: "info", msg: "Case jurisdiction transferred to NDFB Special Operations Division" },
      { ts: "2023-11-02 09:00:00", level: "warn", msg: "All further log entries redacted per National Security Act §47(b)" },
    ]
  },
  {
    id: "CY-2024-0058",
    title: "SYNTHETIC SWARM",
    status: "OPEN",
    category: "Disinformation / Influence Operation",
    desc: "Coordinated inauthentic behavior network of 12,000+ AI-generated personas spreading election disinformation across 6 social platforms. Content factory identified in three countries. Ongoing operation.",
    date: "2024-04-02",
    lead: "Agent R. Chen",
    severity: 78,
    tags: ["AI-Generated", "Disinformation", "Botnets", "Elections"],
    evidence: [
      { icon: "🤖", name: "PERSONA_FINGERPRINT_DB.json",    desc: "Database of 12,447 synthetic accounts identified via stylometric analysis and behavioral clustering. 94% confidence score.", meta: "Analyzed: 2024-04-05 | Tool: SynthDetect v3", status: "ev-verified" },
      { icon: "🖼️", name: "GENERATED_FACES_SAMPLE.zip",     desc: "1,200 profile photos confirmed as GAN-generated. Detection via pixel artifact analysis and reverse image search.", meta: "Tool: FaceForensics++ | Confidence: 98.3%", status: "ev-verified" },
      { icon: "📊", name: "CONTENT_SPREAD_ANALYSIS.xlsx",   desc: "Mapping of disinformation narrative spread across platforms. Shows coordinated amplification bursts every 4 hours.", meta: "Platforms: 6 | Period: Jan–Apr 2024", status: "ev-verified" },
      { icon: "🌐", name: "CONTENT_FARM_IP_CLUSTER",        desc: "47 IPs attributed to content generation infrastructure. Two clusters in Eastern Europe, one in Southeast Asia.", meta: "Confidence: Medium | Geolocation: Approximate", status: "ev-pending" },
    ],
    timeline: [
      { time: "2024-01-15", event: "Narrative Emergence",    detail: "Platform trust-and-safety teams flagged unusual posting pattern around electoral topic. Forwarded to NDFB." },
      { time: "2024-02-03", event: "Network Discovery",      detail: "Graph analysis revealed 12,000+ interconnected accounts with coordinated posting within sub-second windows." },
      { time: "2024-02-28", event: "AI Attribution",         detail: "Stylometric and linguistic analysis confirmed content is LLM-generated. Specific model signature partially identified." },
      { time: "2024-03-15", event: "Infrastructure Traced",  detail: "API calls traced to three cloud hosting providers across two jurisdictions. Subpoenas issued." },
      { time: "2024-04-02", event: "Case Formalized",        detail: "NDFB opens formal investigation. Coordination with international partners initiated." },
      { time: "ONGOING",    event: "Active Monitoring",      detail: "Network still partially operational. Takedowns coordinated with platforms in rolling waves to avoid alerting operators." },
    ],
    suspects: [
      { avatar: "🏭", alias: "MILL OPERATOR",    handle: "@content_phantom",  detail: "Suspected operator of content generation infrastructure. LLM API keys traced to payments from offshore account.", threat: "threat-high" },
      { avatar: "📢", alias: "AMPLIFIER-1",       handle: "@signal_ghost_7",   detail: "Human actor managing 200+ accounts manually. Directs narrative focus. Located via metadata slip in one post.", threat: "threat-med" },
      { avatar: "💼", alias: "FUNDER-UNKNOWN",    handle: "[UNATTRIBUTED]",    detail: "Financial backer identified via payment trail. No direct digital footprint. Intelligence suggests political affiliation.", threat: "threat-high" },
    ],
    logs: [
      { ts: "2024-04-02 09:00:00", level: "info", msg: "Case CY-2024-0058 formally opened — SYNTHETIC SWARM" },
      { ts: "2024-04-02 10:15:33", level: "warn", msg: "New narrative cluster detected: 847 posts in 11 minutes — Amplification event" },
      { ts: "2024-04-03 14:22:00", level: "info", msg: "Platform A: 4,120 accounts suspended — Coordination confirmed" },
      { ts: "2024-04-04 08:00:00", level: "warn", msg: "Network adapting — 3,200 new accounts detected with modified behavior patterns" },
      { ts: "2024-04-05 16:00:00", level: "info", msg: "International partners briefed — Europol, FBI Cyber Division" },
    ]
  },
  {
    id: "CY-2023-0241",
    title: "OPERATION NEON SERPENT",
    status: "CLOSED",
    category: "Ransomware / Extortion",
    desc: "RaaS (Ransomware-as-a-Service) group NEON SERPENT paralyzed three hospital networks across two states. $8.2M demanded. Encryption key recovered via law enforcement action. Two affiliates arrested.",
    date: "2023-08-14",
    lead: "Agent M. Torres",
    severity: 88,
    tags: ["Ransomware", "Healthcare", "RaaS", "Critical Infrastructure"],
    evidence: [
      { icon: "🔐", name: "RANSOMWARE_BINARY_v4.2.exe",   desc: "NEON SERPENT ransomware executable. AES-256 + RSA-2048 encryption. Built on modified LockBit codebase.", meta: "Size: 1.8 MB | Compile time: 2023-08-10 02:33 UTC", status: "ev-verified" },
      { icon: "💬", name: "RANSOM_NOTE.txt",               desc: "Ransom demand with Bitcoin address. Demanded $8.2M within 72 hours. Hospitals refused to pay.", meta: "File recovered from: 1,847 endpoints", status: "ev-verified" },
      { icon: "🔓", name: "DECRYPTION_KEY_RECOVERED.key", desc: "Master decryption key extracted from seized affiliate server. All encrypted hospital files successfully recovered.", meta: "Key length: 4096-bit RSA | Recovery date: 2023-08-28", status: "ev-verified" },
      { icon: "💳", name: "CRYPTO_PAYMENT_TRAIL.pdf",     desc: "Blockchain analysis of prior ransom payments from other victims. Trail leads to exchange accounts linked to suspects.", meta: "Total tracked: $23.4M across 7 prior attacks", status: "ev-verified" },
    ],
    timeline: [
      { time: "2023-08-14 02:17", event: "Ransomware Deployed",    detail: "Encryption began simultaneously across 3 hospital networks. 1,847 endpoints locked. EHR systems offline." },
      { time: "2023-08-14 06:00", event: "Hospitals Declare Emergency", detail: "Patients diverted to other facilities. Surgeries postponed. Manual operations initiated. FBI and NDFB notified." },
      { time: "2023-08-15 09:00", event: "Negotiation Monitored",  detail: "Law enforcement observed ransom chat. Payment refused per federal guidance. Deadline passed." },
      { time: "2023-08-21 14:00", event: "Affiliate Server Seized", detail: "International operation seized RaaS affiliate server in Eastern Europe. Decryption keys recovered." },
      { time: "2023-08-28 08:00", event: "Systems Restored",       detail: "All 1,847 endpoints successfully decrypted. Full system restore completed over 7 days." },
      { time: "2023-09-03",       event: "Arrests Made",            detail: "Two RaaS affiliates arrested in coordinated action. Third at large. Core NEON SERPENT developers still unidentified." },
    ],
    suspects: [
      { avatar: "🐍", alias: "SERPENT-ADMIN", handle: "@ns_core",     detail: "Core developer of NEON SERPENT ransomware kit. Unknown identity. Communicates only via encrypted forums.", threat: "threat-high" },
      { avatar: "🔥", alias: "AFFILIATE-7",   handle: "@ember_lock",  detail: "Ransomware affiliate. Handled initial access via phishing. Arrested in Bucharest. Sentenced 11 years.", threat: "threat-med" },
      { avatar: "💰", alias: "CASHOUT-K",     handle: "@krypto_exit", detail: "Cryptocurrency cashout specialist. Converted ransom payments. Arrested via exchange KYC records.", threat: "threat-med" },
    ],
    logs: [
      { ts: "2023-08-14 02:17:04", level: "crit", msg: "MASS ENCRYPTION EVENT DETECTED — Hospital network METRO-HEALTH-01" },
      { ts: "2023-08-14 02:17:09", level: "crit", msg: "MASS ENCRYPTION EVENT DETECTED — Hospital network RIVERSIDE-MEDICAL" },
      { ts: "2023-08-14 02:17:15", level: "crit", msg: "MASS ENCRYPTION EVENT DETECTED — Hospital network ST-ANNE-GENERAL" },
      { ts: "2023-08-14 06:15:00", level: "info", msg: "FBI Cyber Division engaged — NDFB co-investigation initiated" },
      { ts: "2023-08-21 14:00:00", level: "info", msg: "Foreign affiliate server seized — DECRYPTION KEYS RECOVERED" },
      { ts: "2023-08-28 08:00:00", level: "info", msg: "All affected endpoints decrypted — Restoration complete" },
      { ts: "2023-09-03 10:00:00", level: "info", msg: "Case status: CLOSED — 2 subjects in custody, 1 at large" },
    ]
  },
  {
    id: "CY-2024-0072",
    title: "PROJECT HOLLOW BANK",
    status: "OPEN",
    category: "Banking Trojan / Identity Theft",
    desc: "Sophisticated mobile banking trojan deployed via fake currency exchange apps. 28,000+ victims across 11 countries. $14.7M drained from accounts. Malware overlays legitimate banking apps with credential-harvesting screens.",
    date: "2024-05-01",
    lead: "Agent S. Okafor",
    severity: 81,
    tags: ["Banking Trojan", "Mobile Malware", "Identity Theft", "Mass Victims"],
    evidence: [
      { icon: "📱", name: "TROJAN_APK_FOREXPRO.apk",       desc: "Fake 'ForexPro' app from third-party store. Contains banking trojan with overlay attack capability targeting 47 banking apps.", meta: "Size: 12.4 MB | Downloads before removal: 84,000", status: "ev-verified" },
      { icon: "🗃️", name: "C2_VICTIM_DATABASE.sql",         desc: "Seized C2 server database containing harvested credentials for 28,441 victims. Includes bank account numbers, PINs, and SS numbers.", meta: "Records: 28,441 | Jurisdictions: 11 countries", status: "ev-verified" },
      { icon: "📸", name: "OVERLAY_SCREENS_CAPTURE.zip",    desc: "Screenshots of fake overlay interfaces perfectly mimicking major bank apps' login screens. Pixel-perfect copies.", meta: "Banks targeted: 47 | App stores: 3 unofficial", status: "ev-verified" },
      { icon: "🌍", name: "VICTIM_GEO_HEATMAP.png",         desc: "Geographic distribution of identified victims. Highest concentration in EU, North America, and Southeast Asia.", meta: "Status: Active — new victims identified daily", status: "ev-pending" },
    ],
    timeline: [
      { time: "2024-01-08", event: "First Victims Report",    detail: "Financial institutions report unusual pattern of unauthorized transfers. All victims had recently installed new apps." },
      { time: "2024-02-14", event: "Malware Identified",      detail: "Reverse engineering of suspicious APK confirms banking trojan. ForexPro app flagged. App stores notified." },
      { time: "2024-03-01", event: "C2 Located",              detail: "Command-and-control server identified via malware network traffic. Hosted on bulletproof hosting provider." },
      { time: "2024-04-10", event: "C2 Seized",               detail: "Server seized with international cooperation. 28,441 victim records recovered. Victims being notified." },
      { time: "2024-05-01", event: "Investigation Expanded",  detail: "Case escalated — new trojan variant (v2.1) detected in the wild. Operators still active." },
      { time: "ONGOING",    event: "Active Hunt",              detail: "Tracking operator infrastructure. Three IPs attributed. Extradition treaty discussions initiated." },
    ],
    suspects: [
      { avatar: "🏗️", alias: "HOLLOW-DEV",    handle: "@apk_phantom",    detail: "Lead Android developer. Coded the overlay engine. Code style matches previous banking trojan from 2021.", threat: "threat-high" },
      { avatar: "🌐", alias: "DISTRIBUTE-X",  handle: "@3rdstore_boss",   detail: "Controls third-party app distribution channels. Paid influencers to promote the fake app.", threat: "threat-med" },
      { avatar: "🏧", alias: "MULE-MASTER",   handle: "@cashflow_999",    detail: "Coordinates network of 200+ money mules who receive and forward stolen funds. Partially identified.", threat: "threat-high" },
    ],
    logs: [
      { ts: "2024-05-01 08:00:00", level: "info", msg: "Case CY-2024-0072 formalized — HOLLOW BANK investigation expanded" },
      { ts: "2024-05-01 10:34:22", level: "warn", msg: "New malware variant v2.1 detected — adds 12 new banking app targets" },
      { ts: "2024-05-02 14:00:00", level: "info", msg: "Victim notification process initiated — 28,441 individuals and institutions" },
      { ts: "2024-05-03 09:22:11", level: "warn", msg: "Money mule network active — $340,000 in movement detected since server seizure" },
      { ts: "2024-05-04 16:00:00", level: "info", msg: "Extradition discussions initiated with two foreign jurisdictions" },
    ]
  }
];
